In [1]:
import numpy as np

#### Задание 1

In [10]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
 mean_a = np.mean(a, axis = 0) 
mean_a

array([2. , 8.4])

#### Задание 2

In [14]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3 

In [17]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [18]:
a_centered_sp

8.0

In [20]:
N = a.shape[0]
N

5

In [21]:
div_res = a_centered_sp / (N - 1)
div_res

2.0